language: go
go:
    #    - 1.3
    - 1.4

# let us have speedy Docker-based Travis workers
sudo: false

install:
    - export GOPATH=${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH
    - export PATH=${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH
    - go get code.google.com/p/go.tools/cmd/vet

script:
    - go vet ./...
    - go test -v -race ./...
